"""add time_window_start and time_window_end to service_requests

Revision ID: 2678bb3519f2
Revises: 
Create Date: 2026-04-09 12:35:19.252818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2678bb3519f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_requests', sa.Column('time_window_start', sa.Time(), nullable=True))
    op.add_column('service_requests', sa.Column('time_window_end', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_requests', 'time_window_end')
    op.drop_column('service_requests', 'time_window_start')
    # ### end Alembic commands ###
